[package]
name = "grAMF"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "*"
winit = "*"
glam = "*"
bytemuck = { version = "*", features = ["derive"] }
pollster = "*"
egui-wgpu = "0.33.3"
egui = "0.33.3"
egui-winit = "0.33.3"
petgraph = "0.8.3"
redb = "3.1.0"
colorcet = "0.2.2"
polars = "0.53.0"
geo = "0.32.0"
