[package]
name = "grAMF"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "*"
winit = "*"
glam = "*"
bytemuck = { version = "*", features = ["derive"] }
pollster = "*"
egui-wgpu = "0.33.3"
egui = "0.33.3"
egui-winit = "0.33.3"
petgraph = "0.8.3"
redb = "3.1.0"
colorcet = "0.2.2"
polars = { version = "*", features = ["lazy", "is_in"]}
geo = "0.32.0"
serde = "1.0.228"
serde_json = "1.0.149"
rstar = "0.12.2"
